#!/usr/bin/env node
/**
 * Reads version from package.json and writes src/version.ts.
 * Run as part of `npm run prebuild`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, "..", "package.json"), "utf8"));
const version = pkg.version ?? "unknown";

writeFileSync(
	join(__dirname, "..", "src", "version.ts"),
	`// Auto-generated by prebuild — do not edit\nexport const VERSION = "${version}";\n`,
);
